[package]
name = "piarch-a-data-export"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.0-rc.2"
dotenv = "0.15.0"
once_cell = "1.7.2"
csv = "1.1.6"
serde_json = "1.0"
serde = "1.0.150"

[dependencies.mongodb]
version = "2.3.1"
default-features = false
features = ["sync"]
